export const mapFrancToLocale = (langCode:string) => {
    switch (langCode) {
        case 'eng': return 'en-US'; // English (United States)
        case 'spa': return 'es-ES'; // Spanish (Spain)
        case 'fra': return 'fr-FR'; // French (France)
        case 'deu': return 'de-DE'; // German (Germany)
        case 'ita': return 'it-IT'; // Italian (Italy)
        case 'por': return 'pt-PT'; // Portuguese (Portugal)
        case 'zho': return 'zh-CN'; // Chinese (Simplified, China)
        case 'rus': return 'ru-RU'; // Russian (Russia)
        case 'jpn': return 'ja-JP'; // Japanese (Japan)
        case 'kor': return 'ko-KR'; // Korean (South Korea)
        case 'nld': return 'nl-NL'; // Dutch (Netherlands)
        case 'tur': return 'tr-TR'; // Turkish (Turkey)
        case 'ara': return 'ar-SA'; // Arabic (Saudi Arabia)
        case 'hin': return 'hi-IN'; // Hindi (India)
        case 'ben': return 'bn-BD'; // Bengali (Bangladesh)
        case 'vie': return 'vi-VN'; // Vietnamese (Vietnam)
        case 'tha': return 'th-TH'; // Thai (Thailand)
        case 'swe': return 'sv-SE'; // Swedish (Sweden)
        case 'fin': return 'fi-FI'; // Finnish (Finland)
        case 'dan': return 'da-DK'; // Danish (Denmark)
        case 'nor': return 'no-NO'; // Norwegian (Norway)
        case 'pol': return 'pl-PL'; // Polish (Poland)
        case 'ukr': return 'uk-UA'; // Ukrainian (Ukraine)
        case 'hun': return 'hu-HU'; // Hungarian (Hungary)
        case 'ces': return 'cs-CZ'; // Czech (Czech Republic)
        case 'ron': return 'ro-RO'; // Romanian (Romania)
        case 'gre': return 'el-GR'; // Greek (Greece)
        case 'heb': return 'he-IL'; // Hebrew (Israel)
        case 'ind': return 'id-ID'; // Indonesian (Indonesia)
        case 'tam': return 'ta-IN'; // Tamil (India)
        case 'tel': return 'te-IN'; // Telugu (India)
        case 'mal': return 'ml-IN'; // Malayalam (India)
        case 'urd': return 'ur-PK'; // Urdu (Pakistan)
        case 'fas': return 'fa-IR'; // Persian (Iran)
        case 'bul': return 'bg-BG'; // Bulgarian (Bulgaria)
        case 'slv': return 'sl-SI'; // Slovenian (Slovenia)
        case 'hrv': return 'hr-HR'; // Croatian (Croatia)
        case 'lit': return 'lt-LT'; // Lithuanian (Lithuania)
        case 'lav': return 'lv-LV'; // Latvian (Latvia)
        case 'est': return 'et-EE'; // Estonian (Estonia)
        case 'isl': return 'is-IS'; // Icelandic (Iceland)
        case 'srp': return 'sr-RS'; // Serbian (Serbia)
        case 'bos': return 'bs-BA'; // Bosnian (Bosnia and Herzegovina)
        case 'mkd': return 'mk-MK'; // Macedonian (North Macedonia)
        case 'sqi': return 'sq-AL'; // Albanian (Albania)
        case 'mya': return 'my-MM'; // Burmese (Myanmar)
        case 'khm': return 'km-KH'; // Khmer (Cambodia)
        case 'lao': return 'lo-LA'; // Lao (Laos)
        case 'mon': return 'mn-MN'; // Mongolian (Mongolia)
        case 'cat': return 'ca-ES'; // Catalan (Spain)
        case 'eus': return 'eu-ES'; // Basque (Spain)
        case 'glg': return 'gl-ES'; // Galician (Spain)
        case 'mlt': return 'mt-MT'; // Maltese (Malta)
        case 'ibo': return 'ig-NG'; // Igbo (Nigeria)
        case 'yor': return 'yo-NG'; // Yoruba (Nigeria)
        case 'hau': return 'ha-NE'; // Hausa (Niger)
        case 'zul': return 'zu-ZA'; // Zulu (South Africa)
        case 'xho': return 'xh-ZA'; // Xhosa (South Africa)
        case 'sna': return 'sn-ZW'; // Shona (Zimbabwe)
        case 'nya': return 'ny-MW'; // Chichewa (Malawi)
        case 'som': return 'so-SO'; // Somali (Somalia)
        case 'amh': return 'am-ET'; // Amharic (Ethiopia)
        case 'tir': return 'ti-ER'; // Tigrinya (Eritrea)
        case 'tgk': return 'tg-TJ'; // Tajik (Tajikistan)
        case 'pus': return 'ps-AF'; // Pashto (Afghanistan)
        case 'snd': return 'sd-PK'; // Sindhi (Pakistan)
        case 'nep': return 'ne-NP'; // Nepali (Nepal)
        case 'sin': return 'si-LK'; // Sinhala (Sri Lanka)
        case 'uzb': return 'uz-UZ'; // Uzbek (Uzbekistan)
        case 'kaz': return 'kk-KZ'; // Kazakh (Kazakhstan)
        case 'kir': return 'ky-KG'; // Kyrgyz (Kyrgyzstan)
        case 'tur': return 'tr-TR'; // Turkish (Turkey)
        case 'aze': return 'az-AZ'; // Azerbaijani (Azerbaijan)
        case 'geo': return 'ka-GE'; // Georgian (Georgia)
        case 'arm': return 'hy-AM'; // Armenian (Armenia)
        case 'mal': return 'ml-IN'; // Malayalam (India)
        default: return 'en-US'; // If no match is found
    }
};
